@props(['equipment'])
@php
    $icons = [
        'air_conditioning' => 'snowflake',
        'dual_zone_climate' => 'thermometer-sun',
        'heated_seats' => 'heater',
        'electric_seats' => 'sliders-horizontal',
        'leather_seats' => 'armchair',
        'keyless_entry' => 'key-round',
        'cruise_control' => 'gauge',
        'adaptive_cruise_control' => 'radar',
        'parking_sensors' => 'scan-line',
        'parking_camera' => 'camera',
        'abs' => 'disc-3',
        'esp' => 'shield-check',
        'airbags' => 'shield',
        'lane_assist' => 'route',
        'blind_spot_monitor' => 'eye',
        'front_collision_warning' => 'triangle-alert',
        'hill_assist' => 'mountain',
        'navigation' => 'navigation',
        'bluetooth' => 'bluetooth',
        'apple_carplay' => 'smartphone',
        'android_auto' => 'smartphone',
        'usb' => 'usb',
        'premium_sound' => 'volume-2',
        'digital_cockpit' => 'monitor',
        'led_headlights' => 'lightbulb',
        'xenon_headlights' => 'lightbulb',
        'fog_lights' => 'cloud-fog',
        'panoramic_roof' => 'panel-top',
        'alloy_wheels' => 'disc-2',
        'roof_rails' => 'luggage',
        'tow_hook' => 'link',
        'rain_sensor' => 'cloud-rain',
        'light_sensor' => 'sun',
        'start_stop' => 'power',
        'electric_tailgate' => 'package-open',
        'wireless_charging' => 'battery-charging',
        'head_up_display' => 'projector',
    ];
@endphp
<x-lucide-icon :name="$icons[$equipment] ?? 'badge-check'" {{ $attributes }} />
