<?php

use App\Enums\FuelType;
use App\Enums\SellerType;
use App\Enums\TransmissionType;
use App\Enums\UserRole;

return [
    'cities' => [
        'Beograd',
        'Novi Sad',
        'Niš',
        'Kragujevac',
        'Subotica',
        'Pančevo',
        'Čačak',
        'Kraljevo',
        'Novi Pazar',
        'Smederevo',
        'Leskovac',
        'Valjevo',
        'Užice',
        'Zrenjanin',
        'Šabac',
        'Vranje',
        'Požarevac',
        'Sombor',
        'Jagodina',
        'Kikinda',
        'Pirot',
        'Bor',
        'Zaječar',
        'Loznica',
        'Sremska Mitrovica',
        'Ruma',
        'Inđija',
    ],
    'vehicle_brands' => [
        'AC',
        'Acura',
        'Alfa Romeo',
        'Alpina',
        'Alpine',
        'Aro',
        'Asia Motors',
        'Aston Martin',
        'Audi',
        'Austin',
        'Avantier',
        'BAIC',
        'BAW',
        'Bentley',
        'BMW',
        'BYD',
        'Cadillac',
        'Changan',
        'Chery',
        'Chevrolet',
        'Chrysler',
        'Citroen',
        'Cupra',
        'Dacia',
        'Daewoo',
        'Daihatsu',
        'Dayun',
        'Dodge',
        'Dongfeng',
        'DR',
        'DS',
        'Ferrari',
        'Fiat',
        'Ford',
        'Foton',
        'Geely',
        'Genesis',
        'Great Wall',
        'Honda',
        'Hummer',
        'Hyundai',
        'Ineos',
        'Infiniti',
        'Isuzu',
        'JAC Motors',
        'Jaguar',
        'Jeep',
        'Jetour',
        'JMEV',
        'KGM',
        'Kia',
        'Lada',
        'Lamborghini',
        'Lancia',
        'Land Rover',
        'Lexus',
        'Lincoln',
        'Lotus',
        'Lynk & Co',
        'Mahindra',
        'Maserati',
        'Maybach',
        'Mazda',
        'McLaren',
        'Mercedes Benz',
        'Mercury',
        'MG',
        'MINI',
        'Mitsubishi',
        'Moskvitch',
        'Nissan',
        'NSU',
        'Opel',
        'Peugeot',
        'Polestar',
        'Pontiac',
        'Porsche',
        'Renault',
        'Rolls Royce',
        'Rover',
        'Runhorse',
        'Saab',
        'Seat',
        'Seres',
        'Smart',
        'SsangYong',
        'Subaru',
        'Suzuki',
        'SWM',
        'Talbot',
        'Tesla',
        'Toyota',
        'Trabant',
        'Triumph',
        'UAZ',
        'Volkswagen',
        'Volvo',
        'Wartburg',
        'Xiaomi',
        'Yudo Auto',
        'Zastava',
        'Škoda',
        'Ostalo',
    ],
    'roles' => [
        UserRole::User->value => 'Korisnik',
        UserRole::Dealer->value => 'Diler',
        UserRole::Admin->value => 'Administrator',
    ],
    'permissions' => [
        'view admin dashboard' => 'Pristup upravljanju platformom',
        'manage users' => 'Upravljanje korisnicima',
        'ban users' => 'Suspendovanje korisnika',
        'manage roles' => 'Upravljanje nivoima pristupa i dozvolama',
        'moderate listings' => 'Moderacija oglasa',
        'feature listings' => 'Isticanje oglasa',
        'manage dealers' => 'Upravljanje dilerima',
        'view market analytics' => 'Pregled tržišne analitike',
        'create listings' => 'Kreiranje oglasa',
        'manage own listings' => 'Upravljanje sopstvenim oglasima',
        'manage dealer profile' => 'Upravljanje dilerskim profilom',
        'manage favorites' => 'Upravljanje favoritima',
        'manage saved searches' => 'Upravljanje sačuvanim pretragama',
    ],
    'fuel_types' => [
        FuelType::Petrol->value => 'Benzin',
        FuelType::Diesel->value => 'Dizel',
        FuelType::Hybrid->value => 'Hibrid',
        FuelType::Electric->value => 'Električni',
        FuelType::Lpg->value => 'TNG',
    ],
    'transmission_types' => [
        TransmissionType::Manual->value => 'Manuelni',
        TransmissionType::Automatic->value => 'Automatik',
    ],
    'seller_types' => [
        SellerType::Private->value => 'Privatno lice',
        SellerType::Dealer->value => 'Diler',
    ],
    'imports' => [
        'polovni_automobili' => [
            'enabled' => env('POL_AUTO_IMPORT_ENABLED', false),
            'allow_fetch' => env('POL_AUTO_IMPORT_ALLOW_FETCH', false),
            'auto_publish' => env('POL_AUTO_IMPORT_AUTO_PUBLISH', false),
            'owner_email' => env('POL_AUTO_IMPORT_OWNER_EMAIL', 'admin@autoiq.rs'),
            'timeout_seconds' => (int) env('POL_AUTO_IMPORT_TIMEOUT', 15),
            'connect_timeout_seconds' => (int) env('POL_AUTO_IMPORT_CONNECT_TIMEOUT', 10),
            'user_agent' => env('POL_AUTO_IMPORT_USER_AGENT', 'AutoIQ Import Monitor/1.0 (+https://autoiq.rs)'),
            'respectful_delay_ms' => (int) env('POL_AUTO_IMPORT_DELAY_MS', 1500),
        ],
        'mojauto' => [
            'enabled' => env('MOJAUTO_IMPORT_ENABLED', false),
            'allow_fetch' => env('MOJAUTO_IMPORT_ALLOW_FETCH', false),
            'auto_publish' => env('MOJAUTO_IMPORT_AUTO_PUBLISH', true),
            'owner_email' => env('MOJAUTO_IMPORT_OWNER_EMAIL', 'admin@autoiq.rs'),
            'timeout_seconds' => (int) env('MOJAUTO_IMPORT_TIMEOUT', 15),
            'connect_timeout_seconds' => (int) env('MOJAUTO_IMPORT_CONNECT_TIMEOUT', 10),
            'user_agent' => env('MOJAUTO_IMPORT_USER_AGENT', 'AutoIQ Import Monitor/1.0 (+https://autoiq.rs)'),
            'respectful_delay_ms' => (int) env('MOJAUTO_IMPORT_DELAY_MS', 1000),
        ],
    ],
    'contact' => [
        'recipient_email' => env('AUTOIQ_CONTACT_EMAIL', 'kontakt@autoiq.rs'),
    ],
    'listing_equipment' => [
        'comfort' => [
            'label' => 'Komfor',
            'items' => [
                'air_conditioning' => 'Klima',
                'dual_zone_climate' => 'Dvozonska klima',
                'heated_seats' => 'Grejanje sedišta',
                'electric_seats' => 'Električno podešavanje sedišta',
                'leather_seats' => 'Kožna sedišta',
                'keyless_entry' => 'Keyless ulazak i start',
                'cruise_control' => 'Tempomat',
                'adaptive_cruise_control' => 'Adaptivni tempomat',
                'parking_sensors' => 'Parking senzori',
                'parking_camera' => 'Kamera za rikverc',
            ],
        ],
        'safety' => [
            'label' => 'Bezbednost',
            'items' => [
                'abs' => 'ABS',
                'esp' => 'ESP',
                'airbags' => 'Vazdušni jastuci',
                'lane_assist' => 'Pomoć zadržavanja trake',
                'blind_spot_monitor' => 'Praćenje mrtvog ugla',
                'front_collision_warning' => 'Upozorenje na sudar',
                'hill_assist' => 'Pomoć pri kretanju uzbrdo',
            ],
        ],
        'multimedia' => [
            'label' => 'Multimedija',
            'items' => [
                'navigation' => 'Navigacija',
                'bluetooth' => 'Bluetooth',
                'apple_carplay' => 'Apple CarPlay',
                'android_auto' => 'Android Auto',
                'usb' => 'USB priključak',
                'premium_sound' => 'Premium ozvučenje',
                'digital_cockpit' => 'Digitalna instrument tabla',
            ],
        ],
        'exterior' => [
            'label' => 'Spoljašnost i svetla',
            'items' => [
                'led_headlights' => 'LED svetla',
                'xenon_headlights' => 'Xenon svetla',
                'fog_lights' => 'Maglenke',
                'panoramic_roof' => 'Panoramski krov',
                'alloy_wheels' => 'Alu felne',
                'roof_rails' => 'Krovni nosači',
                'tow_hook' => 'Kuka za vuču',
            ],
        ],
        'driver_assistance' => [
            'label' => 'Pomoć vozaču',
            'items' => [
                'rain_sensor' => 'Senzor kiše',
                'light_sensor' => 'Senzor svetla',
                'start_stop' => 'Start-stop sistem',
                'electric_tailgate' => 'Električno otvaranje gepeka',
                'wireless_charging' => 'Bežično punjenje telefona',
                'head_up_display' => 'Head-up displej',
            ],
        ],
    ],
];
