<?php

// Brand and model labels captured from public Polovni Automobili vehicle filters.

return [
    'brands' => [
        'Alfa Romeo',
        'Alpina',
        'Alpine',
        'Aro',
        'Aston Martin',
        'Audi',
        'Avantier',
        'BAIC',
        'BAW',
        'Bentley',
        'BMW',
        'Buick',
        'BYD',
        'Cadillac',
        'Changan',
        'Chery',
        'Chevrolet',
        'Chrysler',
        'Citroen',
        'Cupra',
        'Dacia',
        'Daewoo',
        'Daihatsu',
        'Dayun',
        'Dodge',
        'Dongfeng',
        'DR',
        'DS',
        'Ferrari',
        'Fiat',
        'Ford',
        'Foton',
        'GAZ',
        'Geely',
        'Genesis',
        'GMC',
        'Great Wall',
        'Honda',
        'Hummer',
        'Hyundai',
        'Ineos',
        'Infiniti',
        'Isuzu',
        'JAC Motors',
        'Jaguar',
        'Jeep',
        'Jetour',
        'Jinpeng',
        'JMEV',
        'KGM',
        'Kia',
        'Lada',
        'Lamborghini',
        'Lancia',
        'Land Rover',
        'Lexus',
        'Lincoln',
        'Lotus',
        'Lynk & Co',
        'Mahindra',
        'Maserati',
        'Maybach',
        'Mazda',
        'McLaren',
        'Mercedes Benz',
        'Mercury',
        'MG',
        'MINI',
        'Mitsubishi',
        'Moskvitch',
        'Nissan',
        'Oldsmobile',
        'Opel',
        'Peugeot',
        'Piaggio',
        'Polestar',
        'Polski Fiat',
        'Pontiac',
        'Porsche',
        'Renault',
        'Rolls Royce',
        'Rover',
        'Saab',
        'Seat',
        'Seres',
        'Smart',
        'SsangYong',
        'Subaru',
        'Suzuki',
        'SWM',
        'Tata',
        'Tesla',
        'Toyota',
        'Trabant',
        'UAZ',
        'Vauxhall',
        'Volkswagen',
        'Volvo',
        'Wartburg',
        'Xiaomi',
        'Yudo Auto',
        'Zastava',
        'Škoda',
        'Ostalo',
    ],
    'models' => [
        'Alfa Romeo' => [
            '33',
            '75',
            '145',
            '146',
            '147',
            '156',
            '156 Crosswagon',
            '159',
            '164',
            '166',
            'Alfasud',
            'Brera',
            'Giulia',
            'Giulietta',
            'GT',
            'GTV',
            'Junior',
            'MiTo',
            'Spider',
            'Stelvio',
            'Tonale',
            'Ostalo',
        ],
        'Alpina' => [
            'B 3',
            'D 3',
            'Ostalo',
        ],
        'Alpine' => [
            'A110',
            'Ostalo',
        ],
        'Aro' => [
            'Serija 10',
            'Ostalo',
        ],
        'Aston Martin' => [
            'DB 11',
            'DB 12',
            'DBX',
            'Ostalo',
        ],
        'Audi' => [
            '80',
            '90',
            '100',
            '200',
            'A1',
            'A2',
            'A3',
            'A4',
            'A4 Allroad',
            'A5',
            'A6',
            'A6 Allroad',
            'A7',
            'A8',
            'e-tron',
            'e-tron GT',
            'Q2',
            'Q3',
            'Q4 e-tron',
            'Q5',
            'Q5 e-tron',
            'Q6',
            'Q7',
            'Q8',
            'R8',
            'RS3',
            'RS4',
            'RS5',
            'RS6',
            'RS7',
            'RS e-tron GT',
            'RS Q3',
            'RS Q8',
            'S1',
            'S3',
            'S4',
            'S5',
            'S6',
            'S7',
            'S8',
            'SQ2',
            'SQ5',
            'SQ7',
            'SQ8',
            'TT',
            'TTS',
            'V8',
            'Ostalo',
        ],
        'Avantier' => [
            'Commuter',
            'EX',
            'Ostalo',
        ],
        'BAIC' => [
            'BJ30',
            'EU5',
            'X55',
            'X75',
            'Ostalo',
        ],
        'BAW' => [
            'Brumby',
            'Pony',
            'Ostalo',
        ],
        'Bentley' => [
            'Bentayga',
            'Continental',
            'Ostalo',
        ],
        'BMW' => [
            'Serija 1',
            '114',
            '116',
            '118',
            '120',
            '123',
            '125',
            '128ti',
            'M 135i',
            'M 140i',
            'Serija 2',
            '214',
            '216',
            '218',
            '220',
            '225',
            'M 235i',
            'M 240i',
            'Serija 3',
            '316',
            '318',
            '318 GT',
            '320',
            '320d',
            '320 GT',
            '323',
            '325',
            '325 GT',
            '328',
            '328 GT',
            '330',
            '335',
            'M 340d',
            'M 340i',
            'Compact',
            'Serija 4',
            '418',
            '420',
            '425',
            '428',
            '430',
            '435',
            '440',
            'M440i',
            'Serija 5',
            '518',
            '520',
            '520 GT',
            '523',
            '524',
            '525',
            '528',
            '530',
            '530 GT',
            '535',
            '535 GT',
            '540',
            '545',
            '550',
            'M550',
            'M 550i',
            'Serija 6',
            '620 GT',
            '630',
            '630 GT',
            '633',
            '635',
            '640',
            '640 GT',
            '645',
            '650',
            'Serija 7',
            '725',
            '728',
            '730',
            '735',
            '740',
            '745',
            '750',
            '760',
            'M760e',
            'Serija 8',
            '840',
            '850',
            'M 850i',
            'Serija i',
            'i3',
            'i4',
            'i7',
            'i8',
            'iX',
            'iX1',
            'iX3',
            'Serija M',
            'M2',
            'M3',
            'M4',
            'M5',
            'M6',
            'M8',
            'X3 M',
            'X4 M',
            'X5 M',
            'X6 M',
            'Serija X',
            'X1',
            'X2',
            'X3',
            'X4',
            'X5',
            'X6',
            'X7',
            'XM',
            'Serija Z',
            'Z3',
            'Z4',
            '2002',
            'Ostalo',
        ],
        'Buick' => [
            'Ostalo',
        ],
        'BYD' => [
            'Atto 2',
            'Dolphin',
            'Seal',
            'Seal 5 DM-i',
            'Seal U DM-i',
            'Sealion 7',
            'Ostalo',
        ],
        'Cadillac' => [
            'BLS',
            'CTS',
            'Deville',
            'Eldorado',
            'Escalade',
            'SRX',
            'Ostalo',
        ],
        'Changan' => [
            'CS35 Plus',
            'CS55 Plus',
            'Deepal S05',
            'Deepal S07',
            'UNI-T',
            'Ostalo',
        ],
        'Chery' => [
            'Arrizo 8',
            'Ego',
            'FX',
            'Tengo',
            'Tiggo 4',
            'Tiggo 7',
            'Tiggo 8',
            'Tiggo 9',
            'Ostalo',
        ],
        'Chevrolet' => [
            'Aveo',
            'Camaro',
            'Captiva',
            'Corvette',
            'Cruze',
            'Epica',
            'Kalos',
            'Lacetti',
            'Matiz',
            'Nubira',
            'Orlando',
            'Spark',
            'Tacuma',
            'Trax',
            'Ostalo',
        ],
        'Chrysler' => [
            '300M',
            '300C',
            'Crossfire',
            'Grand Voyager',
            'Le Baron',
            'Neon',
            'PT Cruiser',
            'Sebring',
            'Stratus',
            'Town & Country',
            'Voyager',
            'Ostalo',
        ],
        'Citroen' => [
            '2CV',
            'Ami',
            'AX',
            'Berlingo',
            'BX',
            'C-Aircross',
            'C-Crosser',
            'C-ELYSEE',
            'C-Zero',
            'C1',
            'C2',
            'C3',
            'C3 Aircross',
            'C3 Picasso',
            'C3 pluriel',
            'e-C4',
            'C4',
            'C4 Aircross',
            'C4 Cactus',
            'C4 Grand Picasso',
            'C4 Grand SpaceTourer',
            'C4 Picasso',
            'C4 SpaceTourer',
            'C4X',
            'C5',
            'C5 Aircross',
            'C5X',
            'C6',
            'C8',
            'DS',
            'DS3',
            'DS4',
            'DS5',
            'DS7',
            'Dyane',
            'GS',
            'GSA',
            'Jumpy',
            'Nemo',
            'Saxo',
            'SpaceTourer',
            'Visa',
            'Xantia',
            'XM',
            'Xsara',
            'Xsara Picasso',
            'ZX',
            'Ostalo',
        ],
        'Cupra' => [
            'Ateca',
            'Born',
            'Formentor',
            'Leon',
            'Leon Sportstourer',
            'Tavascan',
            'Terramar',
            'Ostalo',
        ],
        'Dacia' => [
            'Bigster',
            'Dokker',
            'Double',
            'Duster',
            'Jogger',
            'Lodgy',
            'Logan',
            'Nova',
            'Sandero',
            'Solenza',
            'Spring',
            'Stepway',
            'Ostalo',
        ],
        'Daewoo' => [
            'Kalos',
            'Lacetti',
            'Lanos',
            'Leganza',
            'Matiz',
            'Nubira',
            'Tacuma',
            'Tico',
            'Ostalo',
        ],
        'Daihatsu' => [
            'Cuore',
            'Feroza',
            'Materia',
            'Sirion',
            'Terios',
            'YRV',
            'Ostalo',
        ],
        'Dayun' => [
            'DY3',
            'H8',
            'Ostalo',
        ],
        'Dodge' => [
            'Caliber',
            'Challenger',
            'Charger',
            'Durango',
            'Journey',
            'Nitro',
            'RAM',
            'Stealth',
            'Stratus',
            'Viper',
            'Ostalo',
        ],
        'Dongfeng' => [
            'Aeolus',
            'DFSK',
            'Forthing',
            'Voyah',
            'Ostalo',
        ],
        'DR' => [
            'D5',
            'Ostalo',
        ],
        'DS' => [
            '3',
            '4',
            '5',
            '7',
            'Ostalo',
        ],
        'Ferrari' => [
            '296',
            '458 Italia',
            '488',
            '599',
            '812',
            'California',
            'F8',
            'F12',
            'Purosangue',
            'Roma',
            'Ostalo',
        ],
        'Fiat' => [
            '125',
            '126',
            '127',
            '128',
            '500',
            '500e',
            '500C',
            '500L',
            '500X',
            '600',
            '850',
            '1100',
            '1300',
            'Barchetta',
            'Brava',
            'Bravo',
            'Cinquecento',
            'Coupe',
            'Croma',
            'Doblo',
            'EVO',
            'Fiorino',
            'Freemont',
            'Fullback',
            'Grande Panda',
            'Grande Punto',
            'Idea',
            'Linea',
            'Marea',
            'Marengo',
            'Multipla',
            'Palio',
            'Panda',
            'Punto',
            'Qubo',
            'Scudo',
            'Sedici',
            'Seicento',
            'Spider Europa',
            'Stilo',
            'Tempra',
            'Tipo',
            'Ulysse',
            'Uno',
            'Ostalo',
        ],
        'Ford' => [
            'B-Max',
            'C-Max',
            'Cougar',
            'EcoSport',
            'Edge',
            'Escort',
            'Explorer',
            'F 150',
            'F 250',
            'Festiva',
            'Fiesta',
            'Focus',
            'Fusion',
            'Galaxy',
            'Granada',
            'Grand C-Max',
            'Ka',
            'Ka+',
            'Kuga',
            'Maverick',
            'Mondeo',
            'Mustang',
            'Probe',
            'Puma',
            'Ranger',
            'S-Max',
            'Scorpio',
            'Sierra',
            'Street Ka',
            'Taunus',
            'Thunderbird',
            'Tourneo',
            'Tourneo Connect',
            'Grand Tourneo Connect',
            'Tourneo Courier',
            'Tourneo Custom',
            'Transit Connect',
            'Transit Custom',
            'Windstar',
            'Ostalo',
        ],
        'Foton' => [
            'eTunland',
            'Tunland G7',
            'Tunland V7',
            'Tunland V9',
            'Ostalo',
        ],
        'GAZ' => [
            'Ostalo',
        ],
        'Geely' => [
            'Atlas Pro',
            'Cityray',
            'Coolray',
            'EX5',
            'Starray',
            'Ostalo',
        ],
        'Genesis' => [
            'G90',
            'Ostalo',
        ],
        'GMC' => [
            'Sierra',
            'Ostalo',
        ],
        'Great Wall' => [
            'H6',
            'Steed 5',
            'Ostalo',
        ],
        'Honda' => [
            'Accord',
            'Civic',
            'Concerto',
            'CR-V',
            'CR-Z',
            'CRX',
            'e',
            'FR-V',
            'HR-V',
            'Insight',
            'Jazz',
            'Legend',
            'Stream',
            'ZR-V',
            'Ostalo',
        ],
        'Hummer' => [
            'H2',
            'H3',
            'Ostalo',
        ],
        'Hyundai' => [
            'Accent',
            'Atos',
            'Bayon',
            'Coupe',
            'Elantra',
            'Galloper',
            'Getz',
            'H 1',
            'i10',
            'i20',
            'i30',
            'i40',
            'Ioniq',
            'Ioniq 5',
            'Ioniq 6',
            'ix20',
            'ix35',
            'ix55',
            'Kona',
            'Lantra',
            'Matrix',
            'Santa Fe',
            'Santro',
            'Sonata',
            'Terracan',
            'Trajet',
            'Tucson',
            'Veloster',
            'Ostalo',
        ],
        'Ineos' => [
            'Grenadier',
            'Ostalo',
        ],
        'Infiniti' => [
            'FX30',
            'FX35',
            'FX37',
            'Q30',
            'Q50',
            'Q60',
            'Q70',
            'QX30',
            'QX70',
            'Ostalo',
        ],
        'Isuzu' => [
            'D-Max',
            'Trooper',
            'Ostalo',
        ],
        'JAC Motors' => [
            'E30X',
            'T9 EV',
            'Ostalo',
        ],
        'Jaguar' => [
            'E-Pace',
            'E-Type',
            'F-Type',
            'F pace',
            'I-Pace',
            'S-Type',
            'X-Type',
            'XE',
            'XF',
            'XJ',
            'XJ6',
            'XJ8',
            'XKR',
            'Ostalo',
        ],
        'Jeep' => [
            'Avenger',
            'Cherokee',
            'Commander',
            'Compass',
            'Grand Cherokee',
            'Liberty',
            'Patriot',
            'Renegade',
            'Willys',
            'Wrangler',
            'Ostalo',
        ],
        'Jetour' => [
            'Dashing',
            'T1',
            'T2',
            'X70 Plus',
            'Ostalo',
        ],
        'Jinpeng' => [
            'ECO1',
            'Ostalo',
        ],
        'JMEV' => [
            'EV3',
            'EVEasy GSE',
            'Ostalo',
        ],
        'KGM' => [
            'Actyon',
            'Korando',
            'Musso Grand',
            'Rexton',
            'Tivoli',
            'Torres',
            'Ostalo',
        ],
        'Kia' => [
            'Carens',
            'Carnival',
            'cee`d',
            'cee`d sw',
            'Cerato',
            'EV6',
            'Magentis',
            'Niro',
            'Opirus',
            'Optima',
            'Picanto',
            'Pride',
            'pro_cee`d',
            'Retona',
            'Rio',
            'Sephia',
            'Shuma',
            'Sorento',
            'Soul',
            'Sportage',
            'Stonic',
            'Venga',
            'XCeed',
            'Ostalo',
        ],
        'Lada' => [
            '110',
            '111',
            '112',
            '1200',
            '1300',
            '1500',
            '2101',
            '2104',
            '2107',
            'Kalina',
            'Niva',
            'Riva',
            'Samara',
            'Ostalo',
        ],
        'Lamborghini' => [
            'Aventador',
            'Huracan',
            'Urus',
            'Ostalo',
        ],
        'Lancia' => [
            'Beta',
            'Dedra',
            'Delta',
            'Flavia',
            'Kappa',
            'Lybra',
            'Musa',
            'Phedra',
            'Thema',
            'Thesis',
            'Voyager',
            'Ypsilon',
            'Ostalo',
        ],
        'Land Rover' => [
            'Defender',
            'Discovery',
            'Discovery Sport',
            'Freelander',
            'Range Rover',
            'Range Rover Autobiography',
            'Range Rover Evoque',
            'Range Rover Sport',
            'Range Rover Velar',
            'Range Rover Vogue',
            'Serija II',
            'Ostalo',
        ],
        'Lexus' => [
            'ES',
            'IS',
            'IS 200',
            'IS 220',
            'IS 250',
            'IS 300',
            'LS',
            'LS 600h',
            'LS 600h L',
            'NX',
            'RX',
            'RX 300',
            'RX 400',
            'RX 450',
            'RX 500h',
            'Ostalo',
        ],
        'Lincoln' => [
            'Town car',
            'Ostalo',
        ],
        'Lotus' => [
            'Ostalo',
        ],
        'Lynk & Co' => [
            '01',
            '02',
            '08',
            'Ostalo',
        ],
        'Mahindra' => [
            'Goa',
            'Ostalo',
        ],
        'Maserati' => [
            '224',
            '4200',
            'Ghibli',
            'Granturismo',
            'Grecale',
            'Levante',
            'MC20',
            'Quattroporte',
            'Ostalo',
        ],
        'Maybach' => [
            'Ostalo',
        ],
        'Mazda' => [
            '2',
            '3',
            '5',
            '6',
            '6e',
            '121',
            '323',
            '626',
            'B 250',
            'BT-50',
            'CX-3',
            'CX-5',
            'CX-6E',
            'CX-7',
            'CX-30',
            'CX-60',
            'CX-80',
            'MPV',
            'MX-3',
            'MX-5',
            'Premacy',
            'Tribute',
            'Ostalo',
        ],
        'McLaren' => [
            'Artura',
            'Ostalo',
        ],
        'Mercedes Benz' => [
            '180',
            '190',
            'A Klasa',
            'A 140',
            'A 150',
            'A 160',
            'A 170',
            'A 180',
            'A 190',
            'A 200',
            'A 220',
            'A 250',
            'A 35 AMG',
            'A 45 AMG',
            'B Klasa',
            'B 150',
            'B 160',
            'B 170',
            'B 180',
            'B 200',
            'B 220',
            'B 250',
            'C Klasa',
            'C 160',
            'C 180',
            'C 200',
            'C 220',
            'C 230',
            'C 250',
            'C 270',
            'C 280',
            'C 300',
            'C 320',
            'C 32 AMG',
            'C 350',
            'C 350e',
            'C 400',
            'C 43 AMG',
            'C 63 AMG',
            'CE Klasa',
            'CE 230',
            'Citan',
            'CLA Klasa',
            'CLA 180',
            'CLA 180 Shooting Brake',
            'CLA 200',
            'CLA 200 Shooting Brake',
            'CLA 220',
            'CLA 220 Shooting Brake',
            'CLA 250',
            'CLA 250 Shooting Brake',
            'CLA 35 AMG',
            'CLA 45 AMG',
            'CL Klasa',
            'CL 500',
            'CL 63 AMG',
            'CLC Klasa',
            'CLC 180',
            'CLC 200',
            'CLC 220',
            'CLE Klasa',
            'CLE 200',
            'CLE 220d',
            'CLE 300',
            'CLE 53 AMG',
            'CLK Klasa',
            'CLK 200',
            'CLK 220',
            'CLK 230',
            'CLK 240',
            'CLK 270',
            'CLK 320',
            'CLK 500',
            'CLS Klasa',
            'CLS 220',
            'CLS 220 Shooting Brake',
            'CLS 250',
            'CLS 250 Shooting Brake',
            'CLS 300',
            'CLS 320',
            'CLS 350',
            'CLS 350 Shooting Brake',
            'CLS 400',
            'CLS 450',
            'CLS 500',
            'CLS 53 AMG',
            'CLS 55 AMG',
            'CLS 63 AMG',
            'E Klasa',
            'E 124',
            'E 200',
            'E 220',
            'E 240',
            'E 250',
            'E 260',
            'E 270',
            'E 280',
            'E 290',
            'E 300',
            'E 320',
            'E 350',
            'E 400',
            'E 43 AMG',
            'E 450',
            'E 500',
            'E 53 AMG',
            'E 63 AMG',
            'EQA',
            'EQB',
            'EQC 400',
            'EQE',
            'EQS',
            'EQT',
            'EQV',
            'G Klasa',
            'G 300',
            'G 320',
            'G 350',
            'G 400',
            'G 450',
            'G 500',
            'G 55 AMG',
            'G 63 AMG',
            'GL Klasa',
            'GL 320',
            'GL 350',
            'GL 420',
            'GL 63 AMG',
            'GLA Klasa',
            'GLA 180',
            'GLA 200',
            'GLA 220',
            'GLA 250',
            'GLA 250e',
            'GLA 45 AMG',
            'GLB Klasa',
            'GLB 180',
            'GLB 200',
            'GLB 220',
            'GLC Klasa',
            'GLC 200',
            'GLC 220',
            'GLC 250',
            'GLC 300',
            'GLC 350',
            'GLC 400',
            'GLC 43 AMG',
            'GLC 63',
            'GLE Klasa',
            'GLE 250',
            'GLE 300',
            'GLE 350',
            'GLE 400',
            'GLE 43 AMG',
            'GLE 450',
            'GLE 53 AMG',
            'GLE 580',
            'GLE 63 AMG',
            'GLK Klasa',
            'GLK 200',
            'GLK 220',
            'GLK 250',
            'GLK 320',
            'GLK 350',
            'GLS Klasa',
            'GLS 350 D',
            'GLS 400',
            'GLS 450',
            'GLS 580',
            'GLS 600',
            'GLS 63 AMG',
            'GT Klasa',
            'GT',
            'GT 43 AMG',
            'GT 53 AMG',
            'GT 63 AMG',
            'GT-R',
            'GT-S',
            'ML Klasa',
            'ML 230',
            'ML 250',
            'ML 270',
            'ML 280',
            'ML 300',
            'ML 320',
            'ML 350',
            'ML 400',
            'ML 420',
            'ML 430',
            'ML 500',
            'ML 55 AMG',
            'ML 63 AMG',
            'R Klasa',
            'R 280',
            'R 320',
            'R 350',
            'R 500',
            'S Klasa',
            'S 250',
            'S 280',
            'S 300',
            'S 320',
            'S 350',
            'S 400',
            'S 420',
            'S 450',
            'S 500',
            'S 550',
            'S 560',
            'S 560 Maybach',
            'S 580',
            'S 600',
            'S 63 AMG',
            'SL Klasa',
            'SL 280',
            'SL 300',
            'SL 350',
            'SL 380',
            'SL 43 AMG',
            'SL 500',
            'SL 55 AMG',
            'SL 560',
            'SL 600',
            'SL 63 AMG',
            'SLC Klasa',
            'SLC 200',
            'SLC 250',
            'SLC 380',
            'SLK Klasa',
            'SLK 200',
            'SLK 230',
            'SLK 250',
            'SLK 280',
            'SLK 350',
            'T Klasa',
            'V Klasa',
            'Vaneo',
            'W123',
            'W124',
            'X klasa',
            'Ostalo',
        ],
        'Mercury' => [
            'Ostalo',
        ],
        'MG' => [
            '3',
            '4',
            'EHS',
            'HS',
            'MG3',
            'TF',
            'ZR',
            'ZS',
            'ZS EV',
            'Ostalo',
        ],
        'MINI' => [
            '1000',
            'Aceman',
            'Clubman',
            'Cooper',
            'Cooper S',
            'Countryman',
            'John Cooper Works',
            'Paceman',
            'One',
            'Ostalo',
        ],
        'Mitsubishi' => [
            'ASX',
            'Carisma',
            'Colt',
            'Eclipse',
            'Eclipse Cross',
            'Endeavor',
            'Galant',
            'Grandis',
            'i-MiEV',
            'L200',
            'L300',
            'Lancer',
            'Outlander',
            'Pajero',
            'Pajero Pinin',
            'Pajero Sport',
            'Space Gear',
            'Space Star',
            'Space Wagon',
            'Ostalo',
        ],
        'Moskvitch' => [
            '2140',
            'Ostalo',
        ],
        'Nissan' => [
            '100 NX',
            '200 SX',
            '300 ZX',
            'Almera',
            'Almera Tino',
            'Bluebird',
            'Juke',
            'Kubistar',
            'Leaf',
            'Micra',
            'Murano',
            'Navara',
            'Note',
            'Nv200',
            'Pathfinder',
            'Patrol',
            'Pixo',
            'Primera',
            'Pulsar',
            'Qashqai',
            'Qashqai + 2',
            'Terrano',
            'Tiida',
            'Townstar',
            'X-Trail',
            'Ostalo',
        ],
        'Oldsmobile' => [
            'Cutlass',
            'Ostalo',
        ],
        'Opel' => [
            'Adam',
            'Agila',
            'Ampera',
            'Antara',
            'Ascona',
            'Astra',
            'Astra F',
            'Astra G',
            'Astra H',
            'Astra J',
            'Astra K',
            'Astra L',
            'Calibra',
            'Cascada',
            'Combo',
            'Corsa',
            'Corsa A',
            'Corsa B',
            'Corsa C',
            'Corsa D',
            'Corsa E',
            'Corsa F',
            'Crossland X',
            'Frontera',
            'Grandland',
            'Grandland X',
            'GT',
            'Insignia',
            'Kadett',
            'Karl',
            'Manta',
            'Meriva',
            'Monterey',
            'Mokka',
            'Mokka X',
            'Omega',
            'Rekord',
            'Senator',
            'Signum',
            'Tigra',
            'Vectra',
            'Vectra A',
            'Vectra B',
            'Vectra C',
            'Zafira',
            'Ostalo',
        ],
        'Peugeot' => [
            '106',
            '107',
            '108',
            '205',
            '206',
            '206 plus',
            '207',
            '208',
            '301',
            '305',
            '306',
            '307',
            '308',
            '309',
            '404',
            '405',
            '406',
            '407',
            '408',
            '504',
            '508',
            '508 RXH',
            '607',
            '806',
            '807',
            '1007',
            '2008',
            '3008',
            '4007',
            '4008',
            '5008',
            'Bipper',
            'Expert',
            'iOn',
            'Partner',
            'Ranch',
            'RCZ',
            'Rifter',
            'Traveller',
            'Ostalo',
        ],
        'Piaggio' => [
            'Porter',
            'Ostalo',
        ],
        'Polestar' => [
            '2',
            'Ostalo',
        ],
        'Polski Fiat' => [
            '125 P',
            'Ostalo',
        ],
        'Pontiac' => [
            'Firebird',
            'Ostalo',
        ],
        'Porsche' => [
            '718',
            '911',
            '944',
            'Boxster',
            'Cayenne',
            'Cayman',
            'Macan',
            'Panamera',
            'Taycan',
            'Ostalo',
        ],
        'Renault' => [
            '5 E-Tech',
            'Alaskan',
            'Arkana',
            'Austral',
            'Captur',
            'Clio',
            'Espace',
            'Express',
            'Fluence',
            'Grand Espace',
            'Grand Modus',
            'Grand Scenic',
            'Kadjar',
            'Kangoo',
            'Koleos',
            'Laguna',
            'Latitude',
            'Megane',
            'Megane Conquest',
            'Modus',
            'R 4',
            'R 5',
            'R 9',
            'R 10',
            'R 11',
            'R 18',
            'R 19',
            'R 21',
            'R 25',
            'Rafale',
            'Rapid',
            'RX',
            'Safrane',
            'Scenic',
            'Spider',
            'Symbioz',
            'Talisman',
            'Thalia',
            'Twingo',
            'Twizy',
            'Vel Satis',
            'Zoe',
            'Ostalo',
        ],
        'Rolls Royce' => [
            'Cullinan',
            'Flying Spur',
            'Wraith',
            'Ostalo',
        ],
        'Rover' => [
            '25',
            '45',
            '75',
            '100',
            '200',
            '214',
            '618',
            'Streetwise',
            'Ostalo',
        ],
        'Saab' => [
            '900',
            '9000',
            '9-3',
            '9-5',
            'Ostalo',
        ],
        'Seat' => [
            'Alhambra',
            'Altea',
            'Altea XL',
            'Arona',
            'Arosa',
            'Ateca',
            'Cordoba',
            'Exeo',
            'Ibiza',
            'Inca',
            'Leon',
            'Mii',
            'Tarraco',
            'Toledo',
            'Ostalo',
        ],
        'Seres' => [
            '5',
            'Ostalo',
        ],
        'Smart' => [
            '#1',
            'EQ fortwo',
            'ForFour',
            'ForTwo',
            'Roadster',
            'Ostalo',
        ],
        'SsangYong' => [
            'Actyon',
            'Korando',
            'Kyron',
            'Musso',
            'Rexton',
            'Ostalo',
        ],
        'Subaru' => [
            'Crosstrek',
            'Forester',
            'Impreza',
            'Justy',
            'Legacy',
            'Levorg',
            'Outback',
            'Trezia',
            'Tribeca',
            'XV',
            'Ostalo',
        ],
        'Suzuki' => [
            'Alto',
            'Baleno',
            'Celerio',
            'Grand Vitara',
            'Ignis',
            'Jimny',
            'Liana',
            'Maruti',
            'SJ Samurai',
            'Splash',
            'Swift',
            'SX4',
            'SX4 S-Cross',
            'Vitara',
            'Wagon R+',
            'Ostalo',
        ],
        'SWM' => [
            'G01 PRO',
            'G03F',
            'Ostalo',
        ],
        'Tata' => [
            'Safari',
            'Ostalo',
        ],
        'Tesla' => [
            'Model S',
            'Model 3',
            'Model X',
            'Model Y',
            'Ostalo',
        ],
        'Toyota' => [
            '4Runner',
            'Auris',
            'Avensis',
            'Avensis Verso',
            'Aygo',
            'Aygo X',
            'bZ4X',
            'C-HR',
            'Camry',
            'Carina',
            'Celica',
            'Corolla',
            'Corolla Cross',
            'Corolla Verso',
            'FJ',
            'GT86',
            'Highlander',
            'Hilux',
            'iQ',
            'Land Cruiser',
            'Levin',
            'MR2',
            'Picnic',
            'Prius',
            'Prius +',
            'Proace City',
            'Proace City Verso',
            'Proace Verso',
            'RAV 4',
            'Starlet',
            'Supra',
            'Urban Cruiser',
            'Verso',
            'Verso-S',
            'Wildlander',
            'Yaris',
            'Yaris Cross',
            'Yaris Verso',
            'Ostalo',
        ],
        'Trabant' => [
            '601',
            'Ostalo',
        ],
        'UAZ' => [
            '469',
            'Ostalo',
        ],
        'Vauxhall' => [
            'Ostalo',
        ],
        'Volkswagen' => [
            'Amarok',
            'Arteon',
            'Atlas',
            'Bora',
            'Buggy',
            'Buba',
            'Nova Buba',
            'Caddy',
            'Cross Polo',
            'Cross Touran',
            'EOS',
            'Fox',
            'Golf',
            'Golf 1',
            'Golf 2',
            'Golf 3',
            'Golf 4',
            'Golf 5',
            'Golf 6',
            'Golf 7',
            'Golf 7 Alltrack',
            'Golf 8',
            'Golf 8 Alltrack',
            'Golf Plus',
            'Golf Sportsvan',
            'ID.3',
            'ID.4',
            'ID.5',
            'ID.7',
            'Jetta',
            'Lupo',
            'Multivan',
            'Passat',
            'Passat B1',
            'Passat B2',
            'Passat B3',
            'Passat B4',
            'Passat B5',
            'Passat B5.5',
            'Passat B6',
            'Passat B7',
            'Passat B7 Alltrack',
            'Passat B8',
            'Passat B8 Alltrack',
            'Passat B9',
            'Passat CC',
            'Phaeton',
            'Polo',
            'Scirocco',
            'Sharan',
            'T-Cross',
            'T-Roc',
            'Taigo',
            'Tayron',
            'Tiguan',
            'Tiguan Allspace',
            'Touareg',
            'Touran',
            'up!',
            'Vento',
            'Ostalo',
        ],
        'Volvo' => [
            '244',
            '460',
            '740',
            '850',
            '940',
            '945',
            'C30',
            'C70',
            'EX30',
            'S40',
            'S60',
            'S70',
            'S80',
            'S90',
            'V40',
            'V50',
            'V60',
            'V60 Cross Country',
            'V70',
            'V90',
            'V90 Cross Country',
            'XC40',
            'XC60',
            'XC70',
            'XC90',
            'Ostalo',
        ],
        'Wartburg' => [
            '353',
            'Ostalo',
        ],
        'Xiaomi' => [
            'SU7',
            'YU7',
            'Ostalo',
        ],
        'Yudo Auto' => [
            'Air',
            'Yudo 3',
            'Ostalo',
        ],
        'Zastava' => [
            '10',
            '101',
            '128',
            '1300',
            '1500',
            '750',
            '850',
            'AR 55',
            'Florida',
            'Florida In',
            'Koral',
            'Koral In',
            'Poly',
            'Skala 55',
            'Yugo',
            'Yugo 45',
            'Yugo 55',
            'Yugo 60',
            'Yugo 65',
            'Yugo Cabrio',
            'Yugo Ciao',
            'Yugo In L',
            'Yugo Tempo',
            'Ostalo',
        ],
        'Škoda' => [
            '100',
            '120',
            '1000 MB',
            'Citigo',
            'Elroq',
            'Enyaq',
            'Fabia',
            'Favorit',
            'Felicia',
            'Kamiq',
            'Karoq',
            'Kodiaq',
            'Octavia',
            'Praktik',
            'Rapid',
            'Roomster',
            'Scala',
            'Superb',
            'Yeti',
            'Ostalo',
        ],
        'Ostalo' => [
        ],
    ],
];
